apiVersion: apps/v1
kind: Deployment
metadata:
  name: team3-fronted-server
  namespace: test
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/inject: "true" #istio 사이드카 주입 활성화
    spec:
      containers:
      - name: frontend
        image: 061039804626.dkr.ecr.ap-northeast-2.amazonaws.com/team3/final_front_test:jenkins
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: front-secret
              key: node_env
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: front-secret
              key: jwt_secret
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: front-secret
              key: port
        - name: BACKEND_HOST
          valueFrom:
            secretKeyRef:
              name: front-secret
              key: backend_host
        - name: BACKEND_PORT
          valueFrom:
            secretKeyRef:
              name: front-secret
              key: backend_port
        - name: CHATBOT_HOST
          valueFrom:
            secretKeyRef:
              name: front-secret
              key: chatbot_host
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: front-secret
              key: client_id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: front-secret
              key: client_secret
        - name: REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: front-secret
              key: redirect_uri
        - name: JAVASCRIPT_APPKEY
          valueFrom:
            secretKeyRef:
              name: front-secret
              key: javascript_appkey
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: team3-front-svc
  namespace: test
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 9443
    targetPort: 443
