apiVersion: v1
kind: Secret
metadata:
  name: front-secret
  namespace: test
type: Opaque
stringData:
  node_env: "production"
  jwt_secret: "thisIsMySecretKey"
  port: "443"
  backend_host: "team3-back-svc"
  backend_port: "8000"
  chatbot_host: "127.0.0.1"
  client_id: "7hI4IYFb2ETaTtFDe95B"
  client_secret: "1Yt9Y3DRw9"
  redirect_uri: "https://2pp.lion2.nyhhs.com/naverlogin/login"
  javascript_appkey: "7009b67aab0fde3b4078df8af5bcf900"
