apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-ecr-credentials-updater
  namespace: test
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-credentials-updater-sa
          containers:
          - name: cron-ecr-credentials-updater
            # image: amazon/aws-cli:latest
            # image: bitnami/kubectl:latest
            image: heyvaldemar/aws-kubectl
            command:
            - /bin/sh
            - -c
            - |
              aws ecr get-login-password --region ap-northeast-2 | \
              kubectl create secret docker-registry ecr-secret \
              --docker-server=061039804626.dkr.ecr.ap-northeast-2.amazonaws.com \
              --docker-username=AWS \
              --docker-password=$(aws ecr get-login-password \
              --region ap-northeast-2) \
              --dry-run=client -o yaml | kubectl apply -f -
          restartPolicy: OnFailure
