apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-credentials-updater-sa
  namespace: test

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  namespace: test
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "delete", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: test
subjects:
- kind: ServiceAccount
  name: ecr-credentials-updater-sa
  namespace: test
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
