apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/final-team3-2/2024-Final-PJT-CD.git' # git repo URL
    targetRevision: HEAD
    path: 'CD'
  destination:
    server: 'https://kubernetes.default.svc' # 클러스터의 기본 API 서버 주소
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
